version: "3"

services:
  app:
    image: jboss/keycloak:15.0.0
    # isso aki e pra nao perder o que tiver no H2
    # volumes:
    #   - ./.docker/keycloack/data:/opt/jboss/keycloack/standalone/data    
    environment: 
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
    # - KEYCLOACK_IMPORT=/tmp/test-realm-export.json
      - DB_VENDOR=h2
    ports:
    - 8080:8080    